---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: course-app
  namespace: testlab
spec:
  interval: 5m
  # Як поводитися при оновленні (аналог helm upgrade --install)
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      
  # Звідки брати чарт
  chart:
    spec:
      # Шлях всередині Git-репозиторію
      chart: "./charts/course-app"
      # Посилання на сам Git-репозиторій (його створив bootstrap)
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m

  # Ваші Values (перевизначення)
  values:
    replicaCount: 7
    redis:
      enabled: false # Вимикаємо вбудований, бо у нас є Dragonfly
    appConfig:
      redis:
        host: "dragonfly-sample.testlab.svc.k8s.com822.dom"
        port: 6379
