apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: dragonfly-operator
      version: "v1.3.1"
      sourceRef:
        kind: HelmRepository
        name: dragonfly-charts
        namespace: flux-system
  targetNamespace: dragonfly-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
