apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-dev
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 1m
  retryInterval: 1m
  path: "./overlays/development"
  prune: true
  wait: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: development
  postBuild:
    substitute: {}
