apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-prod
  namespace: flux-system
spec:
  dependsOn:              # <--- ДОДАТИ ЦЕ
    - name: infrastructure
  interval: 1m
  retryInterval: 1m
  path: "./overlays/production"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: production
