apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-prod
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 5m
  retryInterval: 1m
  path: "./overlays/production"
  prune: true
  wait: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: production
